# Root logger option
log4j.rootLogger=INFO, stdout

# Console appender
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} - %m%n

# Client logger - enable console and file
# To disable console output, comment out 'stdout' below
log4j.logger.client=INFO, clientFile
#, stdout
log4j.additivity.client=false

# Client file appender
log4j.appender.clientFile=org.apache.log4j.FileAppender
log4j.appender.clientFile.File=client.log
log4j.appender.clientFile.layout=org.apache.log4j.PatternLayout
log4j.appender.clientFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} - %m%n

# Server logger
log4j.logger.server=INFO, serverFile, stdout
log4j.additivity.server=false

# Server-side non-server package loggers
log4j.logger.storage=INFO, serverFile
log4j.additivity.storage=false

log4j.logger.collection=INFO, serverFile
log4j.additivity.collection=false

# Server file appender
log4j.appender.serverFile=org.apache.log4j.FileAppender
log4j.appender.serverFile.File=server.log
log4j.appender.serverFile.layout=org.apache.log4j.PatternLayout
log4j.appender.serverFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} - %m%n